FIND_PATH(VEELIB_INCLUDE_DIR
  NAMES VeeLib/VeeLib.h
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../VeeLib/"
  "${PROJECT_SOURCE_DIR}/extlibs/VeeLib/"
  ${VEELIB_ROOT}
  $ENV{VEELIB_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound VeeLib include at: ${VEELIB_INCLUDE_DIR}.\n")

IF(VEELIB_INCLUDE_DIR)
  SET(VEELIB_FOUND TRUE)
ELSE(VEELIB_INCLUDE_DIR)
  SET(VEELIB_FOUND FALSE)
ENDIF(VEELIB_INCLUDE_DIR)

IF(VEELIB_FOUND)
  MESSAGE(STATUS "Found VeeLib in ${VEELIB_INCLUDE_DIR}")
ELSE(VEELIB_FOUND)
  IF(VEELIB_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find VeeLib library")
  ENDIF(VEELIB_FIND_REQUIRED)
ENDIF(VEELIB_FOUND)

MARK_AS_ADVANCED(
  VEELIB_INCLUDE_DIR
)
